title: "Syed Murtaza Arshad Portfolio"
description: "Ph.D. Candidate specializing in Biomedical Imaging and Machine Learning."
baseurl: "" # Leave this empty for GitHub Pages
url: "https://syedmurtazaarshad.github.io"
theme: minima
author: "Syed Murtaza Arshad"
email: "SyedMurtazaArshad@gmail.com"
social:
  github: "https://github.com/syedmurtazaarshad"
  linkedin: "https://linkedin.com/in/syedmurtazaarshad"
