title: My Portfolio
description: A showcase of my work and projects
baseurl: ""
url: "https://syedmurtazaarshad.github.io"
author:
  name: "Syed Murtaza Arshad"
  email: "your-email@example.com"
theme: "minimal"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - README.md
  - _posts
  - _layouts
  - _includes
  - _sass
  - assets
  - index.html
  - .gitignore
  - Gemfile
  - Gemfile.lock